/**
 * github-pages.js
 * Commits the updated docs/index.html to the repo and pushes to GitHub.
 * GitHub Actions then deploys it to GitHub Pages automatically.
 */

require('dotenv').config();
const simpleGit = require('simple-git');
const path = require('path');
const fs = require('fs');

const ROOT_DIR = path.join(__dirname, '..');
const git = simpleGit(ROOT_DIR);

/**
 * Get the GitHub Pages URL for this repo
 */
function getPagesUrl() {
  const username = process.env.GITHUB_USERNAME || '';
  const repo = process.env.GITHUB_REPO_NAME || 'ai-weekly-monitor';
  if (!username) return `https://your-username.github.io/${repo}/`;
  return `https://${username}.github.io/${repo}/`;
}

/**
 * Commit and push the latest docs/index.html to GitHub
 * GitHub Actions will then deploy it to GitHub Pages
 */
async function deployToGitHubPages() {
  const pagesUrl = getPagesUrl();
  const dateStr = new Date().toISOString().split('T')[0];

  console.log('\n🚀 Deploying to GitHub Pages...');
  console.log(`   URL: ${pagesUrl}`);

  try {
    // Configure git identity if not already set
    try {
      await git.addConfig('user.email', 'ai-monitor-bot@noreply.github.com');
      await git.addConfig('user.name', 'AI Weekly Monitor Bot');
    } catch {
      // Already configured — fine
    }

    // Stage only the docs folder and reports
    await git.add(['docs/', 'reports/']);

    // Check if there are changes to commit
    const status = await git.status();
    if (status.staged.length === 0) {
      console.log('   ℹ️  No changes to commit');
      return { success: true, url: pagesUrl, skipped: true };
    }

    // Commit
    await git.commit(`🤖 Weekly AI briefing — ${dateStr}

Auto-generated by AI Weekly Monitor
Report covers AI tool releases from the past 7 days.
`);

    // Push to main
    await git.push('origin', 'main');

    console.log(`   ✅ Pushed to GitHub — Pages will update in ~30s`);
    console.log(`   🌐 Report URL: ${pagesUrl}`);

    return { success: true, url: pagesUrl };
  } catch (err) {
    console.error(`   ❌ GitHub push failed: ${err.message}`);
    return { success: false, error: err.message, url: pagesUrl };
  }
}

module.exports = { deployToGitHubPages, getPagesUrl };
